Log tidy
cylc/cylc-ui pull request #1275
Opened 2023-04-18 15:07 UTC by oliver-sanders

> **Built Atop:** https://github.com/cylc/cylc-ui/tree/log-tidy

> **Siblings:** https://github.com/cylc/cylc-uiserver/pull/439 & https://github.com/cylc/cylc-flow/pull/5453

> **Supersedes:** #1268 (PR got broke)

Closes #1206
Closes #1251

* Log files:
  * List available log files:
  * Support viewing other workflow log files e.g. `config/` and `install/`.
  * Support viewing logs from previous job submissions.
* Viewing:
  * Support stripping timestamps from logs.
  * Add a workflow/job toggle to switch between workflow and job logs.
  * Remove the search/update button by subscribing reactively.
  * Add a button for refreshing the log file list.
  * Disable the log file input when the file list is loading.
  * Display the path to the log file being viewed.
  * Display the connection status of the subscription and present a reconnect button to handle cat-log failures/timeouts.
* Opening:
  * Support clicking on jobs in the tree view to open the log for the appropriate job.
  * Make jobs click-able in the Graph view.
* Implementation:
  * Unify the `workflow` and `task` arguments into `id`.
  * Switch to using watchers and debounce for log file requests.
  * Use the ViewToolbar for presenting options.
  * Use a skeleton component for the loading state.

![log-view](https://user-images.githubusercontent.com/16705946/232748511-5a012b16-b5b2-44c3-b5b8-56eaf057892c.gif)

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` (and `conda-environment.yml` if present).
- [x] Tests are included (or explain why tests are not needed).
- [ ] `CHANGES.md` entry included if this is a change that can affect users
- [x] [Cylc-Doc](https://github.com/cylc/cylc-doc) pull request opened if required at cylc/cylc-doc/pull/XXXX.
- [x] If this is a bug fix, PR should be raised against the relevant `?.?.x` branch.

2023-04-19 03:47 UTC, hjoliver approved these changes
Really good, the old GUI is really getting is ass kicked at this point. The code LGTM, had a good play with it, no problems seen.

2023-04-19 09:17 UTC, oliver-sanders commented on .gitignore
> +node_modules
I symlink my `node_modules` directory onto a faster (but less permanent) filesystem which makes it look like a file to git.

2023-04-19 10:46 UTC, wxtim commented
Petty issue I've noticed - the refresh-file-list button changes the current file back to the default - can we avoid that?

2023-04-19 11:56 UTC, wxtim approved these changes
Some nice features.

2023-04-19 12:05 UTC, wxtim reviewed
Test failure locally 

  Subscription Component mixin
    ✓ should provide a hook for when the component is created
    1) should provide a hook for when the component is destroyed

2023-04-19 12:08 UTC, wxtim requested changes
Needs tests fixing

2023-04-19 14:28 UTC, oliver-sanders commented
Fixed test & preserved the file selection for the "update log files" button.

2023-04-21 10:19 UTC, wxtim approved these changes
I've done a final check that it all looks functional locally 😄 

Still test failure?

2023-04-21 10:30 UTC, merged