data store: wipe workflow data on reload.
cylc/cylc-ui pull request #1479
Opened 2023-09-15 14:10 UTC by oliver-sanders

The UI side of https://github.com/cylc/cylc-flow/pull/5715

* When a workflow is reloaded or restarted (node restart infers reload), there may be objects left behind in the store which have been wiped out in the scheduler by the configuration change.
* To handle this, we must wipe all objects stored on the workflow (e.g. TaskProxies, TaskDefs, Jobs, etc), and rebuild from scratch.
* Note, we don't need to wipe the data on the Workflow object itself (e.g. port, stateTotals, etc), these things will be refreshed by this or subsequent deltas.

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` (and `conda-environment.yml` if present).
- [ ] Tests are included (or explain why tests are not needed).
- [ ] `CHANGES.md` entry included if this is a change that can affect users
- [x] [Cylc-Doc](https://github.com/cylc/cylc-doc) pull request opened if required at cylc/cylc-doc/pull/XXXX.
- [x] If this is a bug fix, PR should be raised against the relevant `?.?.x` branch.

2023-10-03 12:47 UTC, MetRonnie commented on src/views/SimpleTree.vue
> +fragment workflowData on Workflow {
```suggestion
fragment WorkflowData on Workflow {
```

2023-10-03 12:47 UTC, MetRonnie commented on CHANGES.md
Conflicting

2023-10-04 10:19 UTC, MetRonnie requested changes
Something is going wrong here when you open the graph view at the same time as the tree view. Both stop updating.

2023-10-10 16:06 UTC, oliver-sanders commented on src/services/treeCallback.js
> +      store.commit('workflows/REMOVE_CHILDREN', (deltas.added.workflow.id))
To test, try jamming in `console.log` statements or whatever here to ensure that the `REMOVE_CHILDREN` store method is being called.

2023-10-10 16:07 UTC, oliver-sanders commented on src/views/README.md
> +## Subscriptions
Added some details here as the rules for subscription writing are getting a little complex.

See also https://github.com/cylc/cylc-ui/issues/862 for context, and a possible way to simplify things for view writers.

2023-10-10 16:14 UTC, oliver-sanders commented
Started this again from scratch:

* I've moved the subscriptions out of the common module into the views to which they pertain.
* The idea of the subscription merging interface is that each view only requests the fields it needs so code reuse is not desirable here.
* I've been through the subscriptions and pulled out a number of fields which weren't required by the views which were requesting them.
* I've also added a couple of things in which the views weren't requesting but should have been.
* The tree and table now have different subscriptions containing only the things they need rather than the superset of the two.
* I've added the `reloaded` field for each of the workflow query views (i.e. the views which get their data from the "workflow" subscription). The other subscriptions don't need this field:
  * Application subscription is used for `Workflows`, `Dashboard` & `WorkflowsTable`, since these only request information about the workflow, not about tasks, etc, they don't need to be wiped on reload.
  * Log subscriptions are reload agnostic.
  * The analysis view uses queries not subscriptions so doesn't require this logic.

The tree and graph seem to be playing together nicely.

2023-10-16 14:22 UTC, MetRonnie reviewed
Seems to work well. Spotted a couple of minor issues after a reload which may or may not be specific to this branch

1. Succeeded tasks without jobs (I have a feeling we came across this before)
  
    ![image](https://github.com/cylc/cylc-ui/assets/61982285/f39ec8a9-4bc4-4d2a-89dc-4c4ecd9a5d6b)

2. The Graph View arrow placement went a bit errant for a moment and I got this error and couldn't pan or zoom anymore

    ![image](https://github.com/cylc/cylc-ui/assets/61982285/08718af6-0d5e-42e2-99d9-8c04e1a6ca72)

2023-10-16 14:27 UTC, oliver-sanders commented on src/views/Dashboard.vue
> +fragment Deltas on Deltas {
It's required for subscription merging to work.

2023-10-16 14:29 UTC, MetRonnie commented on src/views/Dashboard.vue
> +fragment Deltas on Deltas {
Is subscription merging done by a library or is it in-house?

2023-10-16 14:29 UTC, oliver-sanders commented on src/views/Table.vue
> +    ...FamilyProxyData
Shouldn't be, though it was before.

2023-10-16 14:31 UTC, oliver-sanders commented
> Succeeded tasks without jobs (I have a feeling we came across this before)

I haven't seen that one in testing, though I have seen https://github.com/cylc/cylc-flow/issues/5215

If you're able to reproduce, could you check whether the job info was sent through in the deltas?

2023-10-16 15:04 UTC, oliver-sanders commented on src/views/Dashboard.vue
> +fragment Deltas on Deltas {
It's in house code that uses a simple system where it treats a GraphQL document as a nested set (which is pretty accurate) and merges like items. So all subscriptions must match the same format to merge correctly. The merged query is logged to the console for debugging purposes.

2023-10-16 15:05 UTC, oliver-sanders commented
I can't reproduce either reported issue?

2023-10-16 15:59 UTC, oliver-sanders commented
Turns out that repeatably reloading the workflow with this branch is a really good way of triggering the firstParent bug.

Tried testing with https://github.com/cylc/cylc-ui/pull/1513 merged in and everything is looking good after 25 reloads:

![Screenshot from 2023-10-16 16-58-34](https://github.com/cylc/cylc-ui/assets/16705946/bd3dd37d-e877-4286-9662-56e1be9f3e6c)

```diff
diff --git a/src/services/treeCallback.js b/src/services/treeCallback.js
index 570c3ac4..1ab9308c 100644
--- a/src/services/treeCallback.js
+++ b/src/services/treeCallback.js
@@ -38,9 +38,11 @@ class CylcTreeCallback extends DeltasCallback {
     // do this, we can end up with nodes in the store which aren't meant to be
     // there and won't get pruned.
     if (deltas.updated?.workflow?.reloaded) {
+      console.warn('REMOVE_CHILDREN')
       store.commit('workflows/REMOVE_CHILDREN', (deltas.updated.workflow.id))
     }
     if (deltas.added?.workflow?.reloaded) {
+      console.warn('REMOVE_CHILDREN')
       store.commit('workflows/REMOVE_CHILDREN', (deltas.added.workflow.id))
     }
   }

```

2023-10-18 12:29 UTC, oliver-sanders commented
@MetRonnie 

* Applied suggestions
* Removed delta fragments from all queries

2023-10-18 15:53 UTC, MetRonnie reviewed
I've tested out again, and the only problem I can see is the jobs disappear on reload (includes running and succeeded jobs) (seems to be at least `latestJob` goes missing?). This does not happen on master / #1513 presumably because the data was not wiped.

2023-10-19 14:49 UTC, MetRonnie approved these changes

2023-10-19 20:56 UTC, hjoliver approved these changes
LGTM, tested as working 👍

2023-10-19 20:56 UTC, merged